### ISSUE TITLE
Where is the XML file?

### ISSUE THREAD

**Issue by martinsmith** [joshuabaker/craft-sitemap#1]
Hi, it's likely me not understanding but i've installed the plugin. Made my adjustments in the control panel.  Click save aaaand... nothing?   I was kind of expecting a file to appear in the root?

Could you expand on your instructions so I know what I should do after installation.

Thanks

**Comment by joshuabaker** [comment]
The route is [added](https://github.com/joshuabaker/craft-sitemap/blob/5a151191294fe2d492db46690aef241a458a64b3/sitemap/SitemapPlugin.php#L89) dynamically. If you request `/sitemap.xml` you should see the XML output. Please re-open if you’re not seeing that.
