### ISSUE TITLE
Error with DateTime when trying to load sitemap.xml

### ISSUE THREAD

**Issue by slelorrain** [joshuabaker/craft-sitemap#11]
Hello, 

I updated from 0.9.0 to 1.0.0-alpha.2 (Craft version: 2.4.2688), and when I go to sitemap.xml, I got the following error:

```
Argument 2 passed to Craft\Sitemap_UrlModel::__construct() must be an instance of DateTimeInterface, instance of Craft\DateTime given, called in /vagrant/craft/plugins/sitemap/services/SitemapService.php on line 99 and defined  
```

If at line 22 in `Sitemap_UrlModel`, I replace `\DateTimeInterface` by `\DateTime`, the error disappears.

Do you think I have something different that produces the error or is it a mistake?

Cheers, 
Simon

**Comment by joshuabaker** [comment]
Are you using the plugin hook?

**Comment by slelorrain** [comment]
No, I'm not.

**Comment by joshuabaker** [comment]
@slelorrain: Does `v1.0.0-alpha.3` work for you?

**Comment by slelorrain** [comment]
Hello, I just installed `v1.0.0-alpha.4` and it works. Thanks.

**Comment by joshuabaker** [comment]
:+1: Thanks for letting me know.
