### ISSUE TITLE
addCategoryGroup Service not working

### ISSUE THREAD

**Issue by rubenwebs** [joshuabaker/craft-sitemap#15]
Hi,

Nice plugin, but the service addCategoryGroup doesn't work.

Your example code is:

$group = craft()->categories->getGroupByHandle('news');
craft()->sitemap->addCategoryGroup($group);

But it doesn't return any categories, because this line isn't right (Line 145 - SitemapService.php):
$criteria->group = $categoryGroup;

The parameter expects a string, but you're putting in the whole CategoryGroupModel instead.
There are two options of fixing:
1. Change the function to:
   public function addCategoryGroup($categoryGroup, $changefreq = null, $priority = null)

And change the example code to:
craft()->sitemap->addCategoryGroup('news');
1. Or change line 145 to:
   $criteria->group = $categoryGroup->handle;

Hope this helps,
Ruben

**Comment by joshuabaker** [comment]
Thanks, Ruben. 

Care to ping over a PR? :wink:

**Comment by rubenwebs** [comment]
Like so?
