### ISSUE TITLE
Include entries from all locales

### ISSUE THREAD

**Issue by aadlani** [joshuabaker/craft-sitemap#2]
Hi,

Really useful plugin, thank you for sharing it. 

Here just a little feature suggestion concerning translations support. As described in the google [webmasters support](https://support.google.com/webmasters/answer/2620865?hl=en), the `sitemap.xml` supports defining the related translation pages, and the format looks like that.

``` xml
  <url>
    <loc>http://www.example.com/english/</loc>
    <xhtml:link 
                 rel="alternate"
                 hreflang="de"
                 href="http://www.example.com/deutsch/"
                 />
    <xhtml:link 
                 rel="alternate"
                 hreflang="de-ch"
                 href="http://www.example.com/schweiz-deutsch/"
                 />
    <xhtml:link 
                 rel="alternate"
                 hreflang="en"
                 href="http://www.example.com/english/"
                 />
  </url>

  <url>
```

I'm checking craft only since yesterday, and I don't know if I could help here. But based on what I saw, we could maybe in `SitemapService.php`, find the list of the translation with:

``` php
craft().i18n.getSiteLocaleIds();
```

and for each `entries` call the `locale()` method and pass it the current locale to check if there's translation for it:

``` php
$entry.locale(locale).first
```

Maybe the `siteUrl` array which is set in `craft/config/general.php` could be used to build the URL, as describe in the [localization guide](http://buildwithcraft.com/docs/localization-guide).

``` php
return array(
    // ...
    'siteUrl' => array(
        'en' => 'http://example.com/en/',
        'de' => 'http://example.com/de/',
    ),
);
```

I don't know if this is helpful or not ;).

Cheers,

Anouar.

**Comment by joshuabaker** [comment]
Hey Anouar, thanks for the suggestion! :wink:

Language is something that’ll be added as soon as I have some time, along with routes (#3).

I think it’ll be a matter of using the `getLocales()` method via the `EntryModel` instances.
