### ISSUE TITLE
sitemap.xml goes blank page in conjunction with htmlcache plugin

### ISSUE THREAD

**Issue by winterstetter** [joshuabaker/craft-sitemap#22]
https://github.com/craftapi/htmlcache/issues/9

**Joshua**, can you help, please?

**Comment by joshuabaker** [comment]
If it appears without the plugin the issue sounds like it lies with that plugin.

It _might_ be the headers as `sitemap_xml.cached.html` is not going to be XML. That plugin should only create `.html` files from `.twig` and `.html` templates, leaving other file extensions intact.

**Comment by winterstetter** [comment]
Makes sense. Thanks, Joshua!

**Comment by joshuabaker** [comment]
👌 😁
