### ISSUE TITLE
Exclude or select post types to be included in sitemap.xml

### ISSUE THREAD

**Issue by danpaquette** [joshuabaker/craft-sitemap#23]
Hola! I thought it would be very useful to be able to select which post types from a section are included in the sitemap.xml. In our particular use case, we have a section called "new", which contains two types, "News Item" and "Press Feature". The news item is a standard post, the press feature just has a short description and links out to the site we were featured on. In the template, we redirect those entries to 404.

However, the URLs still turn up in the sitemap.xml, triggering a warning in GSC. Let me know what you think of this feature. Thanks!

**Comment by joshuabaker** [comment]
You can use the [`renderSitemap`](https://github.com/joshuabaker/craft-sitemap/tree/2c82ae454308042dbf568a6051560c6bd62d6098#rendersitemap) hook in a [plugin](https://craftcms.com/docs/plugins/introduction) and include filtered elements using the [`addElement`](https://github.com/joshuabaker/craft-sitemap/tree/2c82ae454308042dbf568a6051560c6bd62d6098#addelementbaseelementmodel-element-changefreq-priority) service method.

This is untested, but it should be something like this:

``` php
public function renderSitemap()
{
    $criteria = craft()->elements->getCriteria(ElementType::Entry);
    $criteria->section = '';
    $criteria->type = '';

    foreach ($criteria as $element)
    {
        craft()->sitemap->addElement($element, Sitemap_ChangeFrequency::Daily, 0.5);
    }
}
```
