### ISSUE TITLE
Is this plugin still maintained?

### ISSUE THREAD

**Issue by groe** [joshuabaker/craft-sitemap#28]
Hi @joshuabaker, I have noticed that there hasn't been much activity in craft-sitemap lately: My merge-ready and now production-tested [bugfix PR for multi-locale sites](https://github.com/joshuabaker/craft-sitemap/pull/18) is now pending for almost a year, and there are a few other easy to merge PRs and open issues.

What are your plans on this project for the future? Will you be able to look into some of the issues or merge requests?

Craft-sitemap is a great plugin and it would be a real pity if there were no further fixes, new features or support. If you don't have the time to do it, I would be happy to help you out.

In the meantime I have merged most of the open pull requests into [groe/craft-sitemap](https://github.com/groe/craft-sitemap), added a changelog, release feed for plugin update notifications and a few other minor things. Oh and I've tagged it with version 1.0.0 since I have found it battle-tested enough now :smiley: 

Let me know what you think.

**Comment by groe** [comment]
Aside from the other minor changes I have merged these PRs to [groe/craft-sitemap](https://github.com/groe/craft-sitemap):
- #25 Fixed PHP error thrown by Craft\SitemapPlugin::prepSettings() by @mike27cubes
- #18 Multi-locale domain support, fixes #17
- #16 Update addCategoryGroup in SitemapService.php by @rubenwebs
- #20 [bugfix] removed limit on entries fetched with EntryModel by @tcsehv
- #33 Sort elements by priority descending by @johandouma
- [Support for composer](https://github.com/groe/craft-sitemap/pull/3)

**Comment by davidhellmann** [comment]
Thanks!

**Comment by hisnameisjimmy** [comment]
@groe Thank you for maintaining this! Maybe yours should become the official repo at this point.
